spring:
  profiles:
    active:
    - dev
    
---
spring:
  profiles: dev
  application:
    name: microcloud-config-client
eureka:
   client:
     serviceUrl:
       defaultZone: http://root:Achilles@eureka-7001.com:7001/eureka
---
spring:
  profiles: beta
  application:
    name: microcloud-config-client
eureka:
   client:
     serviceUrl:
       defaultZone: http://root:Achilles@eureka-7002.com:7001/eureka